name: Auto-Merge Dependabot

on:
  check_suite:
    types:
      - completed
  pull_request:
    types:
      - labeled
      - opened
      - ready_for_review

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: auto-merge-dependabot
        if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
        uses: ridedott/dependabot-auto-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
